properties:
  - margin_all_side
  - margin_top_bottom_side
  - margin_left_right_side

  - content_position
  - position_text

  - coloumn_desktop
  - coloumn_mobile

  - use_border_image
  - padding_images
  - border_radius

active_fields:
  - title
  - link
  - subtitle
  - body
  - category_id