# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

default: &default
  adapter: <%= ENV['APP_DB'] %>
  encoding: utf8
  reconnect: false
  database: <%= ENV['APP_DB_NAME'] %>
  pool: <%= ENV['APP_DB_POOL'] %>
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PW'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  reconnect: false

test:
  <<: *default
  reconnect: false

staging: 
  <<: *default
  reconnect: true
  
production:
  <<: *default
  reconnect: true