url_media_socials: ["instagram","facebook","twitter","linkedin","whatsapp"]
general_style: ["primary_color", "secondary_color", "background_body", "text_color_body"]
header_style: ["layout", "position", "margin", "padding", "text_color", "nav_mobile_bg"]
meta: ["author", "meta_url", "meta_image", "meta_title", "meta_description", "keywords"]
  